export const USER_REGISTER = "USER_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const ENTREPRISE_REGISTER = "ENTREPRISE_REGISTER";
export const ENTREPRISEREGISTER_SUCCESS = "ENTREPRISEREGISTER_SUCCESS";
export const ENTREPRISEREGISTER_FAIL = "ENTREPRISEREGISTER_FAIL";

export const ENTREPRISE_LOGIN = "ENTREPRISE_LOGIN";
export const ENTREPRISELOGIN_SUCCESS = "ENTREPRISELOGIN_SUCCESS";
export const ENTREPRISELOGIN_FAIL = "ENTREPRISELOGIN_FAIL";

export const GET_PROFILEENTREPRISE = "GET_PROFILEENTREPRISE";
export const GET_PROFILEENTREPRISE_SUCCESS = "GET_PROFILEENTREPRISE_SUCCESS";
export const GET_PROFILEENTREPRISE_FAIL = "GET_PROFILEENTREPRISE_FAIL";

export const GET_OFFRE = "GET_OFFRE";
export const GET_OFFRES = "GET-OFFRES";
export const TOGGLE_FALSE ="TOGGLE_FALSE";
export const TOGGLE_TRUE = "TOGGLE_TRUE";

export const GET_JOBS = "GET_JOBS";
export const GET_JOB = "GET_JOB";
